### ISSUE TITLE
Execute? 

### ISSUE THREAD

**Issue by Ninisi** [ZenLulz/MemorySharp#22]
hi .
I've using your lib to do something fun.
thanks a lot!
but I have a question.
Is AssemblyFactory.Execute() can call a injected funtion too?
when I injected my test dll to another game process and get successful.
I dont know how to call my funtions.
please answer me.
thank you!

@JamesMenetrey

**Comment by JamesMenetrey** [comment]
Hello!

Happy to see you have some fun with memory editing!

You can indeed call your own injected functions with an instance of`AssemblyFactory`. Otherwise, you can also use the `Execute` method of an instance of `RemotePointer`. Do not forget to specify the calling convention if needed.

Cheers!
Jämes
